# Generated by Django 5.0.3 on 2024-03-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
